mongo-url="mongodb://localhost:27017"
# connect to the Elasticsearch REST API at the following node URLs
elasticsearch-urls = ["http://localhost:9200"]
verbose=true

[[mapping]]
namespace= "varann.clinvar"
index= "clinvar"


[[mapping]]
namespace = "varann.exac"
index = "exac"

[[mapping]]
namespace = "varann.variant"
index = "variant"

[[mapping]]
namespace = "varann.intervar"
index = "intervar"

[[mapping]]
namespace = "varann.g1k"
index = "g1k"

[[mapping]]
namespace = "varann.gnomad_exome"
index = "gnomad_exome"

[[mapping]]
namespace = "varann.transcript"
index = "transcript"